### ISSUE TITLE
Have a refresh button on the Library page.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#231] opened 2023-09-12 01:06 UTC
It was frustrating when I first started using the frontend when I realized it wasn't updating as fast as I was making changes on the backend. Through total accident I realized that just clicking the "search" button with nothing in the search field would update\refresh the library. This was not intuitive and led to wasted time/frustration when I was starting out.

I think a refresh button would be nice for the user. 

Also, if there's a setting for how often refreshes happen, it could be nice for the use to configure it (or at least see how often it's set for). This would inform the user and automate them needing to press the refresh button.

**Comment by Yelo420** [comment] 2023-09-18 16:25
Another button only for refresh (i.e. a duplicate of the search button) would be somewhat unnecessary.
How about that the search button adjusts its text depending.
So if the search text box is empty, the text is "Load" instead of "Search".

What do you think of that?

**Comment by Alfagun74** [comment] 2023-09-25 12:01
@Kudjo-Grand?

**Comment by Kudjo-Grand** [comment] 2023-09-26 06:19
I think that's a great idea that makes it clear what the user can expect. 

Good thinking!

**Comment by Alfagun74** [comment] 2023-10-06 12:59
Moved to #264

**Closed by Alfagun74** 2023-10-06 12:59 UTC
Labels: 🔧 feature, 💻 client
