### ISSUE TITLE
Achievements 

### ISSUE THREAD

**Issue by candroid-man** [Phalcode/gamevault-app#421] opened 2024-07-19 05:18 UTC
I don't know if this is even possible, but it would be really cool to have achievements for each game, and every user can collect them. There already exist hooks that trigger achievements in each game that has achievements on Steam, I was thinking that Gamevault could somehow interpret those?

Perhaps they should be editable as well in case you want to import the achievements you already have in Steam or GOG or whatever so you don't have to restart completely.

**Comment by Alfagun74** [comment] 2024-07-24 11:13
Duplicate of https://github.com/Phalcode/gamevault-backend/issues/249

**Closed by Alfagun74** 2024-07-24 11:13 UTC
Labels: 🔧 feature, 💻 client
