### ISSUE TITLE
Have an optional file to tell the frontend which EXE to use by default

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#247] opened 2023-09-20 16:11 UTC
It is pretty common to have multiple exe files after the game install is complete. For the administrator, it is often obvious which exe to use. But other users may not know which one to target. Leading to a frustrating trial and error situation.

Would it be possible to have an optional file in the installed directory that calls out which exe is the default target so the end user doesn't have to do any guessing? perhaps a file called "gamevault.ini" which, if detected, tells the frontend what to target.

If present, the frontend can still allow the user to target different exe files (like it already does now). But, maybe call out the one indicated by the optional file by including "[default]" in the drop down, next to the targeted file.

This would make for a very smooth and simple end user experience.

What do you think?

Note: I package most of my games in the Portable (W_P) format, so I would just include this optional file in my zip. I'm not sure how we'd do this for the Setup (W_S) format.

**Comment by Alfagun74** [comment] 2023-09-20 16:32
Duplicate of https://github.com/Phalcode/gamevault-backend/issues/148

**Closed by Alfagun74** 2023-09-20 16:32 UTC
Labels: 🔧 feature, 💻 client
