### ISSUE TITLE
Extraction failing to start

### ISSUE THREAD

**Issue by Sixdd6** [Phalcode/gamevault-app#436] opened 2024-10-05 03:38 UTC
**Describe the bug**
I've setup several games with password protected 7z files. When the client begins extracting the game it just stalls at 0% and when looking at task manager the 7z process shows 0% CPU usage. I even left it "extracting" for over an hour and it did nothing. I've tested the archive and it works fine through the 7zip file manager by itself so something seems off with using password protected archives.

**To Reproduce**
1 Create a portable game archive with password protection
2 attempt to install the game
3 notice that there is no progress when extracting the game

**Expected behavior**
Expected the game to be extracted and ready to play

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Client Version 1.11.1.0

**Additional context**
I've tried other games without passwords and it works fine in that case so very much seems related to the password. I've also tried with and without the default password field set in the settings. Without the password set I was not prompted to enter one so maybe that is an area for improvement i.e. prompt the user for a password if no default is present.

**Comment by Alfagun74** [comment] 2024-10-06 23:27
Hi!

Would it be possible for you to upload such a file here? Using password 123456? It can be a zipped Textfile if you want, I just need one archive with your settings to reproduce the bug. Make sure to test it yourself aswell. Thanks in advance.

**Comment by Sixdd6** [comment] 2024-10-07 12:56
No problem, here is an archive using the same settings I've been using. Password is as agreed 123456.
https://mega.nz/file/ejpmnRrA#9gHf-2IRxQa4UFMJZZpryce46k2HekPimyMvxIO-w3U

Had to link to it since apparently Github doesn't allow 7z files.

**Comment by Alfagun74** [comment] 2024-10-07 21:40
Hi @Sixdd6,

We’ve resolved the issue you were experiencing, and the fix will be included in the next available version.

**Technical Details for Future Reference:**

The command ``7z l -stl file.7z`` typically outputs the line ``Encrypted = +`` for most encrypted archives. However, in your case, the archive prompts for a password even during **the listing** of files. This may be due to the fact that you have also encrypted the archive's file names.

This caused GameVault to hang when encountering the password prompt.

To work around this, we used the command ``7z l -stl -psomethingrandom file.7z`` to intentionally generate an error. We then parsed the error output (stderr) to determine whether the archive was encrypted.

Thank you for your patience, and please let us know if you have any further questions.

**Closed by Alfagun74** 2024-10-07 21:40 UTC
Labels: 🪲 bug, 💻 client
