### ISSUE TITLE
Idea: Ability to select game version if multiple version exist

### ISSUE THREAD

**Issue by AzrelixJ** [Phalcode/gamevault-app#334] opened 2024-01-13 03:43 UTC
My idea is that if multiple game version exist in a folder that a drop down menu should exist to select which version you want to install.

I have had multiple games where new versions have been available but have not worked correctly and wanted to install the older version, which has been available in the folder, however these cannot be selected to install without removing the newest version and updating the dashboard.

Thank you.

Az

**Comment by Alfagun74** [comment] 2024-01-26 14:03
thanks for the issue contribution, unfortunately it is a duplicate of [this one.](https://github.com/Phalcode/gamevault-backend/issues/236#issue-2057931012)

**Closed by Alfagun74** 2024-01-26 14:03 UTC
Labels: 🔧 feature, 💻 client
