### ISSUE TITLE
Retry once or twice when "something goes wrong with extraction" and auto extract is selected.

### ISSUE THREAD

**Issue by Kudjo-Grand** [Phalcode/gamevault-app#258] opened 2023-10-03 04:52 UTC
If I have selected the "auto extract" option as a user, it might be nice if there is at least one automatic retry if the extraction fails the first time. I've noticed that when there's an issue, usually all I need to do is push the extract button again and it goes through. (I'm not even sure what makes it fail the first time)

Maybe you could allow the user to specify how many retries. (But, I think only one or two is all that's needed. If it fails two or three times in a row, then something is actually wrong and, imho, the extract operation should error out like it does right now)

What do you think?

**Comment by Alfagun74** [comment] 2023-10-04 00:15
I do not like the idea of auto-retrying an extraction. This is very hacky, and from a user experience perspective, it's quite painful and confusing. I would prefer to understand what caused the initial extraction to fail in the first place.

**Comment by Kudjo-Grand** [comment] 2023-10-04 07:08
Is there a way I could get more details that could hint at the cause of the failure? If I knew where to look, maybe I could figure it out. All I know, is that for me and another new user to the server (a friend that I asked to help me test), we regularly have the extraction fail and all we have to do is try it again, manually.

Next time it happens, are there any logs on the frontend app that I could look at?

**Comment by Alfagun74** [comment] 2023-10-04 07:17
Unfortunately, we have no control over the 7zip process. GameVault currently only confirms if it succeeded or failed and the progress output without obtaining more specific information. However, you can achieve the same outcome by using the 7z.exe included with gamevault. Simply run the following command: ``GameVaultProgramFolder/Lib/7z.exe x -y -o ExtractionTargetFolder/ YourGameArchive.7z`` and see if there are any errors.

**Comment by Yelo420** [comment] 2023-10-04 08:35
Maybe the problem is that the filestream has not been completely closed by the 7zip process. Means, if the auto extract starts directly after the download, it comes to a "File is used by another process" exception. 

This would be indicated if this occurs immediately after the start of extraction.

This could be fixed by simply waiting a short time before the extraction starts.

**Comment by Alfagun74** [comment] 2023-10-04 10:47
So we would need to implement a short delay before autoextract begins.

**Comment by Kudjo-Grand** [comment] 2023-10-08 06:50
Good find! That would be great if that simple change fixes this bug. I'll definitely watch in the next version to see if this tweaks solves the misbehavior.

**Closed** 2023-10-09 11:24 UTC
Labels: 🪲 bug, 🔧 feature, 💻 client

**Comment by Alfagun74** [comment] 2023-10-09 11:26
awesome find!
