### ISSUE TITLE
oidc/OAuth support?

### ISSUE THREAD

**Issue by MattyIceee** [Phalcode/gamevault-app#437] opened 2024-10-16 14:31 UTC
**Is your feature request related to a problem? Please describe.**
Some people already have identity managers in their ecosystem (Authentik, Authelia).  These managers can allow sso via oidc with different services. Currently GameVault does not provide a way to pair/create users to the identity manager via oauth

**Describe the solution you'd like**
An oauth integration where users can be created/paired to their identify manager user to allow for sso.

**Comment by Alfagun74** [comment] 2024-10-16 15:48
Duplicate of https://github.com/Phalcode/gamevault-backend/issues/6.

Waiting for volunteers

**Closed by Alfagun74** 2024-10-16 15:48 UTC
Labels: 🔧 feature, 💻 client
