### ISSUE TITLE
Hide website button when no website available

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#222] opened 2023-09-07 22:38 UTC
**Is your feature request related to a problem? Please describe.**
Currently, games with no website defined still show the website button, which does nothing when clicked.

**Describe the solution you'd like**
Hide the button, or show it as disabled with alt text stating "No website available for this game."

**Comment by Alfagun74** [comment] 2023-09-08 05:28
Duplicate of #156

**Closed** 2023-09-08 05:28 UTC
Labels: 🔧 feature, 💻 client
