### ISSUE TITLE
Gracefully handle an unavailable server on GameVault startup

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#212] opened 2023-09-01 01:43 UTC
**Is your feature request related to a problem? Please describe.**
When the GV server is down, and a client attempts to connect, the login authentication remains, but the application is logged out. You need to re-sign in, or restart GV to reauthenticate.

**Describe the solution you'd like**
An "offline mode" which runs as if the user is connected, but with server required features disabled. Passively monitor for the server and reconnect once available.

**Describe alternatives you've considered**
A "cannot connect" popover that prevents use until the server is available, and a button to re-attempt connection. This is a terrible idea.

**Comment by Alfagun74** [comment] 2023-09-05 22:35
Duplicate of #1

**Closed by Alfagun74** 2023-09-05 22:35 UTC
Labels: 🔧 feature, 💻 client
