### ISSUE TITLE
Keypress -> Enter on account login page should submit login information

### ISSUE THREAD

**Issue by KairuByte** [Phalcode/gamevault-app#185] opened 2023-08-15 20:28 UTC
**Describe the bug**
Pressing enter on the account login page should submit login information

**To Reproduce**
1. Go to Settings
2. Click on Login
3. Enter login information
4. Hit enter

**Expected behavior**
Login information is submitted, as if the login button had been clicked.

**Comment by Alfagun74** [comment] 2023-08-15 20:43
Is this Issue only about the missing Keypress -> Enter?

**Comment by Alfagun74** [comment] 2023-08-15 20:44
Makes sense UX-wise but is not a bug, rather a missing feature

**Comment by KairuByte** [comment] 2023-08-15 20:45
Fair enough, I was torn between the two. Yes, that is all the issue is about.

**Comment by Alfagun74** [comment] 2023-08-18 11:38
merged to #191

**Closed by Alfagun74** 2023-08-18 11:38 UTC
Labels: 🔧 feature, 💻 client
